名字：微信
在上
  工作流触发输入：
  日程安排：
    # 代表国际标准时间23点0分，北京时间需要+8小时，代表北京时间上午7点运行
    - : - cron: '0 23 * * *'
工作：
#将工作流程中运行的所有作业组合在一起
  构建：
  #定义名为 build 的作业。子键将定义作业的属性
    运行于：ubuntu-latest
    步骤：
      - 用途：actions/checkout@v2
    
      - 名称: 设置 Python 3.9
        使用：actions/setup-python@v2
        与：
          python-version： 3.9.1
      - 名称：设置时区
        运行： |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - 名称: 安装 pip 软件包
        运行： |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - 名字: 微信
        运行： |
          python3 main.py
